name: Deploy to Tebi S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Deploy to Tebi
        env:
          AWS_REQUEST_CHECKSUM_CALCULATION: when_required
          AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
          AWS_ACCESS_KEY_ID: ${{ secrets.TEBI_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEBI_SECRET_ACCESS_KEY }}
        run: |
          aws s3 --endpoint-url https://s3.tebi.io sync ./content s3://www.7il.de
